# This playbook copies GCP and OCP data to IQE pod and executes a test.
# The playbook performs the following tasks:
# 1. Get pod names with grep
# 2. Fail the task if podname is not found
# 3. Get current date and time
# 4. Set fact log file name
# 5. Set fact dir name
# 6. Create the directory
# 7. Execute the test_api_ocp_on_gcp_ingest_single_source
- name: Copy gcp and ocp data to IQE pod 
  hosts: "{{ target_host }}"
  gather_facts: no
  vars_files: 
    - vars.yml

  tasks:
    - name: Get pod names with grep
      shell: "oc get pods | grep '^iqe' | awk '{print $1}'"
      register: pod_name
      
    - name: fail the task if podname is not found
      fail:
        msg: "{{ pod_name.stderr }}"
      when: pod_name.stdout | length == 0

    - name: Get current date and time
      command: date +'%Y-%m-%d_%H-%M-%S'
      register: current_date_time

    - name: Set fact log file name
      set_fact:
        file_name: "{{ current_date_time.stdout }}"

    - name: set fact dir name 
      set_fact:
        dir_name: test_n_{{ nodes }}_nam_{{ namespaces }}_p_{{ pods }}_v_{{ volumes }}

    - name: Create the directory
      file: 
        path: "$PWD/{{ dir_name }}"
        state: directory

    - name: Execute the test_api_ocp_on_gcp_ingest_single_source
      shell: |
        oc exec {{ pod_name.stdout }} -- sh -c "iqe tests plugin cost_management -k \"{{ test_to_run }}\" -m cost_smoke --log-file {{test_to_run}}_logs.txt"
      register: log_output
     
